### ISSUE TITLE
[REQUEST] Extensions-common suggestions

### ISSUE THREAD

**Issue by AdrienSeon** [Paperback-iOS/extensions-common#28]
Referencing @FramboisePi issue https://github.com/Paperback-iOS/app/issues/255 here as a reminder so it can be followed and closed when someone look into these inconsistencies.

**Comment by AdrienSeon** [comment]
For The [MangaStatus](https://github.com/Paperback-iOS/extensions-common/blob/master/src/models/Manga/index.ts) enumeration, here are the states which could be useful in my opinion: 

- Completed
- Ongoing
- Licensed
- Dropped
- Discontinued
- Hiatus
- Unknown

**Comment by ConradWeiser** [comment]
Would you mind consolidating this information into https://github.com/Paperback-iOS/app/issues/255? There's no need to spread it across multiple requests.

I don't have a problem with the enumeration suggestion! I'll look into getting that adjustment in for 0.6's release

**Comment by AdrienSeon** [comment]
Closed by Paperback-iOS/extensions-common@251cd12
