### ISSUE TITLE
Better documentation

### ISSUE THREAD

**Issue by binyaminyblatt** [Paperback-iOS/extensions-common#52]
I would love to help the community maintain extensions but I have no time to dissect this entire package and figure out how it works if there was better documentation I feel that we would be able to attract more maintainers for extensions and thereby make the community grow better

I'm not sure I'm posting this in the right place but I think we need better documentation across the board

**Comment by celarye** [comment]
+1, it would make it a lot easier for users to get into source development.

However, I rather would see a proper documentation for the newer [0.8 library](https://github.com/Paperback-iOS/paperback-toolchain) instead of the 0.7 library.

**Comment by binyaminyblatt** [comment]
Ok I'll move the issue to the other repository
